---
vector_version: 0.21.1
vector_config_dir: "{{ ansible_user_dir }}/vector_config"
vector_config:
  sources:
    sample_file:
      type: file
      read_from: beginning
      include:
        - /home/alex/logs/*.log
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - sample_file
      endpoints: http://localhost:8123
      database: logs
      table: from_vector
      auth:
        password: netology
        user: vector
      skip_unknown_fields: true
      compression: gzip