{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Memory & Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{device=~\"/dev/sda.+\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"/dev/sda.+\"})",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='nodeexporter'}",
     "legendFormat": "free"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU LA",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "LA_1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "LA_5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "LA_15"
    }
   ]
  },
  {
   "title": "CPU idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (instance)(irate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mode=\"idle\"}[30m])) * 100\n",
     "legendFormat": "utilization%"
    }
   ]
  }
 ]
}