---
vector_version: 0.21.1
vector_config_dir: "{{ ansible_user_dir }}/vector_config"
vector_source_dir: "/var/lib/vector/sample_file"
vector_config:
  sources:
    sample_file:
      type: file
      read_from: beginning
      include:
        - /home/alex/logs/*.log
#  transforms:
#    parse_log:
#      type: json_parser
#      inputs: [sample_file]
#      drop_field: false
#      drop_invalid: true
#      field: message
#    transform_datetime:
#      type: regex_parser
#      inputs: [parse_log]
#      field: timestamp
#      patterns: [^(?P<time_dt>.*)\.(?P<time_ms>.*)$]
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - sample_file
      endpoint: http://localhost:8123
      database: logs
      table: from_vector
      auth:
        password: qwerty
        user: mira
        strategy: basic
      skip_unknown_fields: true
      healthcheck: true
      compression: gzip